version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres # Cambia esto por tu usuario deseado
      POSTGRES_PASSWORD: mysecretpassword # Cambia esto por tu contraseña deseada
      POSTGRES_DB: postgres # Base de datos por defecto para conectarse
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
  app:
    image: mcr.microsoft.com/dotnet/aspnet:8.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9595:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
